service:
  name: serverless-flashcards-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev-v2'}
  region: ${opt:region, 'us-east-1'}

  tracing:
    lambda: true
    apiGateway: true

  environment:
    FLASHCARDS_TABLE: Flashcards-${self:provider.stage}
    IMAGES_S3_BUCKET: wun1-serverless-flashcards-images-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300

custom:
  documentation:
    api:
      info:
        version: v1.0.0
        title: Flashcards API
        description: Serverless backend for Flashcards


functions:
  GetFlashcards:
    handler: src/lambda/http/getFlashcards.handler
    iamRoleStatementsName: getFlashcards-role
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FLASHCARDS_TABLE}
        # Bucket is actually public
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: arn:aws:s3:::${self:provider.environment.IMAGES_S3_BUCKET}/*        

    events:
      - http:
          method: get
          path: flashcards
          cors: true       

  CreateFlashcard:
    handler: src/lambda/http/createFlashcard.handler
    iamRoleStatementsName: createFlashcard-role
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FLASHCARDS_TABLE}
    events:
      - http:
          method: post
          path: flashcards
          cors: true
          request:
            schema:
              application/json: ${file(reqmodels/create-flashcard-request.json)}

  UpdateFlashcard:
    handler: src/lambda/http/updateFlashcard.handler
    iamRoleStatementsName: updateFlashcard-role
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FLASHCARDS_TABLE}    
    events:
      - http:
          method: patch
          path: flashcards/{flashcardId}
          cors: true
          request:
            parameters:
              paths:
                flashcardId: true
            schema:
              application/json: ${file(reqmodels/update-flashcard-request.json)}

  DeleteFlashcard:
    handler: src/lambda/http/deleteFlashcard.handler
    iamRoleStatementsName: deleteFlashcard-role
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FLASHCARDS_TABLE}    
    events:
      - http:
          method: delete
          path: flashcards/{flashcardId}
          cors: true
          request:
            parameters:
              paths:
                flashcardId: true          

  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    iamRoleStatementsName: generateFlashcardUploadUrl-role
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FLASHCARDS_TABLE}
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: arn:aws:s3:::${self:provider.environment.IMAGES_S3_BUCKET}/*
    events:
      - http:
          method: post
          path: flashcards/{flashcardId}/attachment
          cors: true
          request:
            parameters:
              paths:
                flashcardId: true

resources:
  Resources:
    FlashcardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S         
          - AttributeName: flashcardId
            AttributeType: S            
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: flashcardId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.FLASHCARDS_TABLE}

    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.IMAGES_S3_BUCKET}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.IMAGES_S3_BUCKET}/*'
        Bucket: !Ref AttachmentsBucket        